name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["Feature"]
body:
  - type: markdown
    attributes:
      value: |
        ##Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: ❓ Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: Tell us the problem.
    validations:
      required: true
  - type: textarea
    id: Solution
    attributes:
      label: 	💡 Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: 💡 Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 🖼️ Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: 
      value: 
    validations:
      required: false
  
  - type: textarea
    id: Additional 
    attributes:
      label: ℹ️ Additional context
      description: Add any other context about the problem here.
    validations: 
      required: false
  
  - type: textarea
    id: todo
    attributes:
      label: "✅ Todo"
      description: Any things that need to be done or that need to be clarified
      value: |
        - [ ] Remember to add repository label
